---
language: node_js
node_js:
  - "6"
cache:
  directories:
  - node_modules
env:
  - REACT_APP_ETENGINE_URL=https://engine.test
script:
  - npm run coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
